### ISSUE TITLE
Add parsing for different print options

### ISSUE THREAD

**Issue by ShaivPandya** [SCE-Development/Quasar#27]
Create a function that generates a command depending on the given values for the fields (copies, page ranges, etc.) in [`printer/PrintHandler.js`](https://github.com/SCE-Development/Quasar/blob/dev/printer/PrintHandler.js).

### Example
If no page range is specified, it will default to "NA" and thus, no `-P` flag is necessary. If page ranges is specified as "2-4", then the function would return "-P 2-4" which could then be used in the `lp` command. This is currently done at [`printer/PrintHandler.js:46`](https://github.com/SCE-Development/Quasar/blob/da2331f512af416a12f7b1aaef64e3a0fc1b147a/printer/PrintHandler.js#L48).

The same could be done for copies. If the number of copies is 2, the function would return "-n 2" which could then be used in the `lp` command.

**Comment by evanugarte** [comment]
closing because we dont need this atm, also we rewrote the project since this
