### ISSUE TITLE
Monitor printer ink levels with SNMP 

### ISSUE THREAD

**Issue by starphys** [SCE-Development/Quasar#29]
MacOS is able to show the esitmated ink levels of SCE printers when added through System Preferences. How does it work? Wireshark yielded the below result

![image](https://user-images.githubusercontent.com/36345325/157950143-563a074b-d24b-4e98-8566-26d045987129.png)

SNMP! What is it? It looks like we can retrieve ink levels using the protocol [SNMP docs](https://secure.n-able.com/webhelp/nc_7-2-0_cust_en/content/n-central/Services/Services_PrinterTonerLevel.html).

We may be able to use a Node [net-snmp](https://www.npmjs.com/package/net-snmp) library to talk to the printers to grab data on ink levels and other things.

### game plan
- [x] ensure we know how fastapi works
- [x] write some simple snmp code in python to query ink level and page count from the printer
- [x] discuss what metrics appear when the tray is open, or when the printer is out of ink
- [x] learn argparse
- [x] learn good enums in python, combine the metrics with enums
- [x] learn how to add prometheus metrics to a basic fast api
- [x] combine argparse, enums and prometheus to scrape SNMP metrics from the printer

**Comment by evanugarte** [comment]
HP p2015dn SNMP [reference](https://github.com/remetremet/SNMP-OIDs/blob/master/OIDs/Printer-HP-LaserJet-P2055.md)

**Comment by starphys** [comment]
First step merged in https://github.com/SCE-Development/Quasar/pull/31. Now that this functionality is exposed, there are two next steps:
1) Build a dashboard to monitor this data regularly (allowing us to anticipate the need to change ink before it becomes a problem.)
2) Incorporate this into printer selection logic (try to balance ink levels, drain one printer first, always drain the more empty printer, etc).

**Comment by evanugarte** [comment]
closing as this will live outside of quasar shoutout @akshtshrma24

**Comment by evanugarte** [comment]
reference for paper jam
https://oidref.com/1.3.6.1.4.1.11.2.3.9.1.1.2.9

when we do `snmpwalk -v 1 -c public <PRINTER_IP> .1` we get a row below like
```
iso.3.6.1.4.1.11.2.3.9.1.1.2.9.0 = INTEGER: 0
```

the above oid matches the link, just replace `iso` with `1` and remove the trailing `.0`


---
reference for `prtAlertTable` https://mibbrowser.online/mibdb_search.php?mib=Printer-MIB

**Comment by evanugarte** [comment]
reopening this for this 2024 summer internship
