### ISSUE TITLE
Monitor printing metrics with Grafana dashboard

### ISSUE THREAD

**Issue by starphys** [SCE-Development/Quasar#34]
Live dashboards of printer metrics will let us catch issues before they become a problem for members. Printer out of ink? It's on the dashboard. Printer not responding to pings? Dashboard. 

This will roll out in several stages. The first step is to capture basic metrics with Prometheus and expose those on a Grafana dashboard. From there we build custom metrics for our printing system, starting with ink levels (https://github.com/SCE-Development/Quasar/issues/29). Once that's done we can start exposing new metrics that we think will be valuable, as our system allows. 

![image](https://user-images.githubusercontent.com/7348870/163598159-c4131e3b-de68-4575-9005-a04ae6c3502c.png)
image courtesy of @evanugarte

**Comment by evanugarte** [comment]
closing as this will live outside of quasar shoutout @akshtshrma24
